FROM maven:3.9.9-eclipse-temurin-21-jammy AS BUILD_IMAGE

WORKDIR /app
COPY . /app

RUN mvn install
FROM tomcat:10-jdk21

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=BUILD_IMAGE /target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
