trigger:
- main

variables:
  ACR_NAME: 'devreg96'
  IMAGE_TAG: 'latest'
  REPO_APP: 'vprofileapp'
  REPO_WEB: 'vprofileweb'
  REPO_DB: 'vprofiledb'

jobs:
- job: build
  displayName: 'Build and Push Docker Images'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: 'login'
      containerRegistry: 'acr-devreg96-service'

  - script: |
      echo Validating docker-compose config...
      docker-compose config
      echo Building...
      docker-compose build
    displayName: 'Build docker images'

  - script: |
      echo Tagging and pushing images to ACR...
      docker tag vprofileapp $ACR_NAME.azurecr.io/$REPO_APP:$IMAGE_TAG
      docker push $ACR_NAME.azurecr.io/$REPO_APP:$IMAGE_TAG
    displayName: 'Push image'

- job: deploy
  displayName: 'Deploy to App Service'
  dependsOn: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureWebAppContainer@1
    displayName: 'Deploy Docker Image'
    inputs:
      azureSubscription: Azure subscription 1 (2edd3441-9535-4384-9f66-2e3fad269e4c)
      appName: 'webdockerapp'
      containers: 'devreg96.azurecr.io/vprofileapp:latest'
