trigger:
- main

variables:
  ACR_NAME: 'devreg96'
  IMAGE_TAG: 'latest'
  REPO_APP: 'vprofileapp'
  REPO_WEB: 'vprofileweb'
  REPO_DB: 'vprofiledb'

jobs:
- job: build
  displayName: 'Build and Push Docker Images'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: login
        containerRegistry: 'acr-devreg96-service'  # نام Service Connection به ACR

    - script: |
        echo Installing Docker Compose...
        DOCKER_COMPOSE_VERSION="1.29.2"
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        /usr/local/bin/docker-compose --version
      displayName: 'Install Docker Compose'

    - script: |
        echo Building images with Docker Compose...
        /usr/local/bin/docker-compose -f docker-compose.yml build
      displayName: 'Build images'

    - script: |
        echo Tagging and pushing images to ACR...
        docker tag vprocontainers/vprofileapp $(ACR_NAME).azurecr.io/$(REPO_APP):$(IMAGE_TAG)
        docker tag vprocontainers/vprofileweb $(ACR_NAME).azurecr.io/$(REPO_WEB):$(IMAGE_TAG)
        docker tag vprocontainers/vprofiledb $(ACR_NAME).azurecr.io/$(REPO_DB):$(IMAGE_TAG)

        docker push $(ACR_NAME).azurecr.io/$(REPO_APP):$(IMAGE_TAG)
        docker push $(ACR_NAME).azurecr.io/$(REPO_WEB):$(IMAGE_TAG)
        docker push $(ACR_NAME).azurecr.io/$(REPO_DB):$(IMAGE_TAG)
      displayName: 'Push images to ACR'

    - script: docker images
      displayName: 'List Docker Images'

- job: deploy
  displayName: 'Deploy to Azure App Service (vprofileapp)'
  dependsOn: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy vprofileapp Container'
      inputs:
        azureSubscription: 'Azure subscription 1 (2edd3441-9535-4384-9f66-2e3fad269e4c)'  # نام Service Connection به Azure
        appName: 'webdockerapp'
        containers: 'devreg96.azurecr.io/vprofileapp:latest'
