steps:
  # 1. کلون ریپو
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/suuenz/vprofile-project.git

  # 2. نصب Docker Compose
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose --version

  # 3. بیلد ایمیج‌ها با Docker Compose
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker-compose -f docker-compose.yml build
      

  # 4. Push Docker images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_REPO}/vprofileapp:1.0']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_REPO}/vprofileweb:1.0']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_REPO}/vprofiledb:1.0']


substitutions:
  _PROJECT_ID: 'eighth-vehicle-466618-g2'
  _REPO: 'vprofile-images'
 # _VERSION: 'v1.0'

options:
  logging: CLOUD_LOGGING_ONLY
