version: "3.3"

services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: 084317777937.dkr.ecr.eu-north-1.amazonaws.com/vprofiledb:latest
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: 
      context: ./Docker-files/app/multistage
    image: 084317777937.dkr.ecr.eu-north-1.amazonaws.com/vprofileapp:latest
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb:
    build: 
      context: ./Docker-files/web
    image: 084317777937.dkr.ecr.eu-north-1.amazonaws.com/vprofileweb:latest
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
